<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0d6efd"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="CRM"><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/pwa-icon.svg" type="image/svg+xml"><title>Вход — CRM</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><style>body{background:#f4f6f9}.login-card{border-radius:18px}.app-mark{width:58px;height:58px;border-radius:16px;background:#0d6efd;color:#fff;display:flex;align-items:center;justify-content:center;font-size:30px;margin-bottom:16px}.form-control,.form-select{min-height:48px}.btn{min-height:48px}.login-mode-note{font-size:.84rem}@media(max-width:575.98px){.login-wrap{padding:14px}.login-card .card-body{padding:22px!important}}</style></head><body><div class="container login-wrap"><div class="row justify-content-center align-items-center min-vh-100"><div class="col-md-5 col-lg-4"><div class="card login-card border-0 shadow"><div class="card-body p-4"><div class="app-mark"><i class="bi bi-buildings"></i></div><h3 class="mb-1">CRM организаций</h3><p class="text-secondary mb-4">Войдите в рабочее пространство своей организации</p>@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif<form method="post" action="{{ route('login.perform') }}">@csrf<div class="mb-3"><label class="form-label">Код организации</label><input id="organizationCode" name="organization_code" class="form-control" value="{{ old('organization_code') }}" placeholder="Например: zcrb" autocomplete="organization"><div class="form-text">Для входа суперадминистратора оставьте поле пустым.</div></div>
<div id="organizationStatus" class="small text-muted mb-3"></div>
<div class="mb-3" id="superadminLoginBlock"><label class="form-label">Логин суперадминистратора</label><input id="superadminLogin" name="login" class="form-control" value="{{ old('login') }}" autocomplete="username"></div>
<div class="mb-3 d-none" id="emailLoginBlock"><label class="form-label">Email</label><input id="emailLogin" name="email" type="email" class="form-control" value="{{ old('email') }}" autocomplete="username"></div>
<div class="mb-3 d-none" id="fioLoginBlock"><label class="form-label">ФИО сотрудника</label><select id="fioLogin" name="user_id" class="form-select"><option value="">Выберите сотрудника...</option></select><div class="form-text login-mode-note">В списке отображаются активные сотрудники выбранной организации.</div></div>
<div class="mb-3"><label class="form-label">Пароль</label><input name="password" type="password" class="form-control" required autocomplete="current-password"></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="remember" value="1" id="remember"><label class="form-check-label" for="remember">Запомнить меня</label></div><button class="btn btn-primary w-100">Войти</button></form><button id="installPwaLogin" class="btn btn-outline-primary w-100 mt-3 d-none"><i class="bi bi-phone me-2"></i>Установить приложение</button></div></div></div></div></div>
<script>
const orgInput=document.getElementById('organizationCode');
const statusEl=document.getElementById('organizationStatus');
const superBlock=document.getElementById('superadminLoginBlock');
const emailBlock=document.getElementById('emailLoginBlock');
const fioBlock=document.getElementById('fioLoginBlock');
const superInput=document.getElementById('superadminLogin');
const emailInput=document.getElementById('emailLogin');
const fioSelect=document.getElementById('fioLogin');
let orgTimer=null;
function setMode(mode){superBlock.classList.toggle('d-none',mode!=='superadmin');emailBlock.classList.toggle('d-none',mode!=='email');fioBlock.classList.toggle('d-none',mode!=='fio');superInput.required=mode==='superadmin';emailInput.required=mode==='email';fioSelect.required=mode==='fio';}
async function loadOrganizationLogin(){const code=orgInput.value.trim();if(!code){setMode('superadmin');statusEl.textContent='Вход суперадминистратора';return;}statusEl.textContent='Проверка организации...';try{const r=await fetch(`/login/organization-info?code=${encodeURIComponent(code)}`,{headers:{'Accept':'application/json'}});const data=await r.json();if(!r.ok)throw new Error(data.message||'Организация не найдена');statusEl.textContent=data.organization?`Организация: ${data.organization}`:'';if(data.mode==='fio'){setMode('fio');const oldId='{{ old('user_id') }}';fioSelect.innerHTML='<option value="">Выберите сотрудника...</option>'+(data.users||[]).map(u=>`<option value="${u.id}" ${String(u.id)===String(oldId)?'selected':''}>${escapeHtml(u.name)}${u.position?' — '+escapeHtml(u.position):''}</option>`).join('');}else{setMode('email');}}catch(e){setMode('email');statusEl.textContent=e.message;}}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
orgInput.addEventListener('input',()=>{clearTimeout(orgTimer);orgTimer=setTimeout(loadOrganizationLogin,350)});loadOrganizationLogin();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}))}let pwaPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();pwaPrompt=e;document.getElementById('installPwaLogin').classList.remove('d-none')});document.getElementById('installPwaLogin').addEventListener('click',async()=>{if(!pwaPrompt)return;pwaPrompt.prompt();await pwaPrompt.userChoice;pwaPrompt=null;document.getElementById('installPwaLogin').classList.add('d-none')});
</script></body></html>