<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0d6efd"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="CRM"><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/pwa-icon.svg" type="image/svg+xml"><title>Вход — CRM</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet"><style>body{background:#f4f6f9}.login-card{border-radius:18px}.app-mark{width:58px;height:58px;border-radius:16px;background:#0d6efd;color:#fff;display:flex;align-items:center;justify-content:center;font-size:30px;margin-bottom:16px}.form-control,.form-select{min-height:48px}.btn{min-height:48px}.login-mode-note{font-size:.84rem}.fio-picker{position:relative}.fio-results{max-height:260px;overflow-y:auto;border:1px solid #dee2e6;border-radius:.5rem;background:#fff;margin-top:.35rem}.fio-option{display:block;width:100%;text-align:left;border:0;background:#fff;padding:.65rem .75rem;border-bottom:1px solid #f0f0f0}.fio-option:last-child{border-bottom:0}.fio-option:hover,.fio-option.active{background:#f0f6ff}.fio-option .fio-name{font-weight:600}.fio-option .fio-position{font-size:.82rem;color:#6c757d}.fio-empty{padding:.8rem;color:#6c757d;text-align:center}.fio-selected{font-size:.85rem;margin-top:.4rem}@media(max-width:575.98px){.login-wrap{padding:14px}.login-card .card-body{padding:22px!important}}</style></head><body><div class="container login-wrap"><div class="row justify-content-center align-items-center min-vh-100"><div class="col-md-5 col-lg-4"><div class="card login-card border-0 shadow"><div class="card-body p-4"><div class="app-mark"><i class="bi bi-buildings"></i></div><h3 class="mb-1">CRM организаций</h3><p class="text-secondary mb-4">Войдите в рабочее пространство своей организации</p>@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif<form method="post" action="{{ route('login.perform') }}">@csrf<div class="mb-3"><label class="form-label">Код организации</label><input id="organizationCode" name="organization_code" class="form-control" value="{{ old('organization_code') }}" placeholder="Например: zcrb" autocomplete="organization"><div class="form-text">Для входа суперадминистратора оставьте поле пустым.</div></div>
<div id="organizationStatus" class="small text-muted mb-3"></div>
<div class="mb-3" id="superadminLoginBlock"><label class="form-label">Логин суперадминистратора</label><input id="superadminLogin" name="login" class="form-control" value="{{ old('login') }}" autocomplete="username"></div>
<div class="mb-3 d-none" id="emailLoginBlock"><label class="form-label">Email</label><input id="emailLogin" name="email" type="email" class="form-control" value="{{ old('email') }}" autocomplete="username"></div>
<div class="mb-3 d-none" id="fioLoginBlock"><label class="form-label">ФИО сотрудника</label><div class="fio-picker"><div class="input-group"><span class="input-group-text bg-white"><i class="bi bi-search"></i></span><input id="fioSearch" type="text" class="form-control" placeholder="Начните вводить ФИО или должность..." autocomplete="off"></div><input type="hidden" id="fioLogin" name="user_id" value="{{ old('user_id') }}"><div id="fioResults" class="fio-results d-none"></div><div id="fioSelected" class="fio-selected text-muted">Сотрудник не выбран</div></div><div class="form-text login-mode-note">Начните вводить фамилию, имя или должность. В поиске только активные сотрудники выбранной организации.</div></div>
<div class="mb-3"><label class="form-label">Пароль</label><input name="password" type="password" class="form-control" required autocomplete="current-password"></div><div class="form-check mb-3"><input class="form-check-input" type="checkbox" name="remember" value="1" id="remember"><label class="form-check-label" for="remember">Запомнить меня</label></div><button class="btn btn-primary w-100">Войти</button></form><button id="installPwaLogin" class="btn btn-outline-primary w-100 mt-3 d-none"><i class="bi bi-phone me-2"></i>Установить приложение</button></div></div></div></div></div>
<script>
const orgInput=document.getElementById('organizationCode');
const statusEl=document.getElementById('organizationStatus');
const superBlock=document.getElementById('superadminLoginBlock');
const emailBlock=document.getElementById('emailLoginBlock');
const fioBlock=document.getElementById('fioLoginBlock');
const superInput=document.getElementById('superadminLogin');
const emailInput=document.getElementById('emailLogin');
const fioInput=document.getElementById('fioLogin');
const fioSearch=document.getElementById('fioSearch');
const fioResults=document.getElementById('fioResults');
const fioSelected=document.getElementById('fioSelected');
let fioUsers=[];
let orgTimer=null;
function setMode(mode){superBlock.classList.toggle('d-none',mode!=='superadmin');emailBlock.classList.toggle('d-none',mode!=='email');fioBlock.classList.toggle('d-none',mode!=='fio');superInput.required=mode==='superadmin';emailInput.required=mode==='email';fioInput.required=mode==='fio';}
function normalizeText(v){return String(v||'').toLocaleLowerCase('ru-RU').replace(/ё/g,'е').trim();}
function renderFioResults(){const q=normalizeText(fioSearch.value);const rows=fioUsers.filter(u=>!q||normalizeText((u.name||'')+' '+(u.position||'')).includes(q)).slice(0,100);if(!rows.length){fioResults.innerHTML='<div class="fio-empty">Сотрудник не найден</div>';fioResults.classList.remove('d-none');return;}fioResults.innerHTML=rows.map(u=>`<button type="button" class="fio-option" data-id="${u.id}"><div class="fio-name">${escapeHtml(u.name)}</div>${u.position?`<div class="fio-position">${escapeHtml(u.position)}</div>`:''}</button>`).join('');fioResults.classList.remove('d-none');}
function selectFioUser(id){const u=fioUsers.find(x=>String(x.id)===String(id));if(!u)return;fioInput.value=u.id;fioSearch.value=u.name;fioSelected.innerHTML=`Выбран: <b>${escapeHtml(u.name)}</b>${u.position?' — '+escapeHtml(u.position):''}`;fioSelected.classList.remove('text-muted');fioResults.classList.add('d-none');}
fioSearch.addEventListener('focus',renderFioResults);
fioSearch.addEventListener('input',()=>{fioInput.value='';fioSelected.textContent='Сотрудник не выбран';fioSelected.classList.add('text-muted');renderFioResults();});
fioResults.addEventListener('click',e=>{const button=e.target.closest('.fio-option');if(button)selectFioUser(button.dataset.id);});
document.addEventListener('click',e=>{if(!fioBlock.contains(e.target))fioResults.classList.add('d-none');});
async function loadOrganizationLogin(){const code=orgInput.value.trim();if(!code){setMode('superadmin');statusEl.textContent='Вход суперадминистратора';fioUsers=[];return;}statusEl.textContent='Проверка организации...';try{const r=await fetch(`/login/organization-info?code=${encodeURIComponent(code)}`,{headers:{'Accept':'application/json'}});const data=await r.json();if(!r.ok)throw new Error(data.message||'Организация не найдена');statusEl.textContent=data.organization?`Организация: ${data.organization}`:'';if(data.mode==='fio'){setMode('fio');fioUsers=Array.isArray(data.users)?data.users:[];const oldId='{{ old('user_id') }}';if(oldId)selectFioUser(oldId);else{fioInput.value='';fioSearch.value='';fioSelected.textContent=`Доступно сотрудников: ${fioUsers.length}. Начните вводить ФИО.`;fioSelected.classList.add('text-muted');fioResults.classList.add('d-none');}}else{setMode('email');fioUsers=[];}}catch(e){setMode('email');fioUsers=[];statusEl.textContent=e.message;}}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
orgInput.addEventListener('input',()=>{clearTimeout(orgTimer);orgTimer=setTimeout(loadOrganizationLogin,350)});loadOrganizationLogin();
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}))}let pwaPrompt=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();pwaPrompt=e;document.getElementById('installPwaLogin').classList.remove('d-none')});document.getElementById('installPwaLogin').addEventListener('click',async()=>{if(!pwaPrompt)return;pwaPrompt.prompt();await pwaPrompt.userChoice;pwaPrompt=null;document.getElementById('installPwaLogin').classList.add('d-none')});
</script></body></html>