@extends('layouts.app')
@section('title','Отсутствия и замещения — CRM ЗЦРБ')
@section('header','Отсутствия и замещения')
@push('styles')
<link href="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.css" rel="stylesheet">
<style>#absenceCalendar{background:#fff;padding:16px;border-radius:16px;box-shadow:0 1px 3px rgba(16,24,40,.08)}.fc-event{cursor:pointer}</style>
@endpush
@section('content')
<div class="d-flex gap-2 flex-wrap mb-3">
  <select id="absenceUserFilter" class="form-select" style="max-width:320px"><option value="">Все сотрудники</option>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select>
  <button class="btn btn-primary ms-auto" data-bs-toggle="modal" data-bs-target="#absenceModal"><i class="bi bi-calendar-x me-1"></i>Добавить отсутствие</button>
  <button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#substitutionModal"><i class="bi bi-arrow-left-right me-1"></i>Назначить заместителя</button>
</div>
<div class="row g-4">
  <div class="col-xl-8"><div id="absenceCalendar"></div></div>
  <div class="col-xl-4"><div class="card border-0 shadow-sm"><div class="card-header bg-white"><b>Замещения</b></div><div id="substitutionList" class="list-group list-group-flush"><div class="p-4 text-center text-muted">Загрузка...</div></div></div></div>
</div>

<div class="modal fade" id="absenceModal" tabindex="-1"><div class="modal-dialog"><form id="absenceForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Отсутствие сотрудника</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Сотрудник</label><select name="user_id" class="form-select" required>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Причина</label><select name="type" class="form-select"><option value="vacation">Отпуск</option><option value="sick_leave">Больничный</option><option value="business_trip">Командировка</option><option value="training">Обучение</option><option value="other">Другое</option></select></div><div class="row g-3"><div class="col-6"><label class="form-label">С</label><input type="date" name="date_from" class="form-control" required></div><div class="col-6"><label class="form-label">По</label><input type="date" name="date_to" class="form-control" required></div></div><div class="mt-3"><label class="form-label">№ документа/приказа</label><input name="document_number" class="form-control"></div><div class="mt-3"><label class="form-label">Комментарий</label><textarea name="comment" class="form-control" rows="3"></textarea></div><div id="absenceError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Сохранить</button></div></form></div></div>

<div class="modal fade" id="substitutionModal" tabindex="-1"><div class="modal-dialog"><form id="substitutionForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Замещение сотрудника</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Кого замещают</label><select name="absent_user_id" class="form-select" required>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Кто замещает</label><select name="substitute_user_id" class="form-select" required>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select></div><div class="row g-3"><div class="col-6"><label class="form-label">С</label><input type="date" name="date_from" class="form-control" required></div><div class="col-6"><label class="form-label">По</label><input type="date" name="date_to" class="form-control" required></div></div><div class="mt-3"><label class="form-label">Комментарий</label><textarea name="comment" class="form-control" rows="3"></textarea></div><div id="substitutionError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Назначить</button></div></form></div></div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/index.global.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.15/locales-all.global.min.js"></script>
<script>
function escA(v){return $('<div>').text(v??'').html()}
let absenceCalendar;
function loadSubstitutions(){$.get('{{ route('availability.substitutions') }}',r=>{let h='';r.forEach(x=>{h+=`<div class="list-group-item"><div class="fw-semibold">${escA(x.absent_user?.last_name+' '+x.absent_user?.first_name)} → ${escA(x.substitute_user?.last_name+' '+x.substitute_user?.first_name)}</div><div class="small text-muted">${new Date(x.date_from).toLocaleDateString('ru-RU')} — ${new Date(x.date_to).toLocaleDateString('ru-RU')}</div>${x.comment?`<div class="small mt-1">${escA(x.comment)}</div>`:''}</div>`});$('#substitutionList').html(h||'<div class="p-4 text-center text-muted">Замещений нет</div>')})}
document.addEventListener('DOMContentLoaded',()=>{absenceCalendar=new FullCalendar.Calendar(document.getElementById('absenceCalendar'),{locale:'ru',firstDay:1,height:'auto',initialView:'dayGridMonth',headerToolbar:{left:'prev,next today',center:'title',right:'dayGridMonth,listMonth'},buttonText:{today:'Сегодня',month:'Месяц',list:'Список'},events:function(info,ok,fail){$.get('{{ route('availability.events') }}',{start:info.startStr,end:info.endStr,user_id:$('#absenceUserFilter').val()}).done(ok).fail(fail)},eventDidMount:function(info){const t=info.event.extendedProps.type;info.el.style.backgroundColor={vacation:'#0d6efd',sick_leave:'#dc3545',business_trip:'#6f42c1',training:'#198754',other:'#6c757d'}[t]||'#6c757d';info.el.style.borderColor='transparent';info.el.title=(info.event.extendedProps.department||'')+(info.event.extendedProps.comment?' · '+info.event.extendedProps.comment:'')}});absenceCalendar.render();$('#absenceUserFilter').on('change',()=>absenceCalendar.refetchEvents())});
$('#absenceForm').on('submit',function(e){e.preventDefault();$.post('{{ route('availability.absences.store') }}',Object.fromEntries(new FormData(this).entries())).done(()=>{this.reset();bootstrap.Modal.getInstance('#absenceModal').hide();absenceCalendar.refetchEvents()}).fail(x=>$('#absenceError').removeClass('d-none').text(x.responseJSON?.message||'Ошибка'))});
$('#substitutionForm').on('submit',function(e){e.preventDefault();$.post('{{ route('availability.substitutions.store') }}',Object.fromEntries(new FormData(this).entries())).done(()=>{this.reset();bootstrap.Modal.getInstance('#substitutionModal').hide();loadSubstitutions()}).fail(x=>$('#substitutionError').removeClass('d-none').text(x.responseJSON?.message||'Ошибка'))});
loadSubstitutions();
</script>
@endpush
