@extends('layouts.app')
@section('title',$department->name.' — 360°')
@section('header','Подразделение 360°')
@section('content')
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="d-flex gap-3 align-items-start flex-wrap"><div class="flex-grow-1"><div class="text-muted small">{{ $department->short_name }}</div><h2 class="mb-1">{{ $department->name }}</h2><div class="text-muted">{{ $department->parent?->name }}</div></div><button class="btn btn-outline-primary" onclick="openEntityCollab('department',{{ $department->id }},'Материалы подразделения: {{ addslashes($department->name) }}')"><i class="bi bi-chat-paperclip me-1"></i>Файлы и комментарии</button><a href="{{ route('departments.page') }}" class="btn btn-outline-secondary"><i class="bi bi-arrow-left me-1"></i>К структуре</a></div></div></div>

<div class="row g-3 mb-4">
@foreach([
 ['Сотрудников',$stats['employees'],'bi-people',''],['Открытых задач',$stats['open_tasks'],'bi-check2-square',''],['Просрочено',$stats['overdue'],'bi-exclamation-triangle','text-danger'],['На проверке',$stats['review'],'bi-clipboard-check','text-warning'],['Критических',$stats['critical'],'bi-exclamation-octagon','text-danger'],['Выполнено за месяц',$stats['completed_month'],'bi-check-circle','text-success'],['Отсутствуют сегодня',$stats['absent_today'],'bi-calendar-x',''],['Вакантно ставок',$stats['vacant_rate'],'bi-person-plus','text-primary']
] as $s)
<div class="col-6 col-md-3 col-xl"><div class="card stat-card h-100"><div class="card-body"><i class="bi {{ $s[2] }} {{ $s[3] }}"></i><div class="text-muted small mt-2">{{ $s[0] }}</div><div class="fs-3 fw-bold {{ $s[3] }}">{{ $s[1] }}</div></div></div></div>
@endforeach
</div>

<div class="row g-4">
<div class="col-xl-7"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white d-flex align-items-center"><b>Сотрудники</b><span class="badge text-bg-light border ms-2">{{ $users->count() }}</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Сотрудник</th><th>Должность</th><th>Руководитель</th><th></th></tr></thead><tbody>@forelse($users as $u)<tr><td><b>{{ $u->full_name }}</b></td><td>{{ $u->activeAssignments->first()?->staffingPosition?->position?->name ?? $u->position }}</td><td>{{ $u->manager?->full_name ?? '—' }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('employees.profile',$u) }}">360°</a></td></tr>@empty<tr><td colspan="4" class="text-center py-4 text-muted">Нет доступных сотрудников</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-xl-5"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white"><b>Штатное расписание</b></div><div class="card-body"><div class="row g-2 mb-3"><div class="col-4"><div class="border rounded p-3"><div class="small text-muted">План</div><b>{{ $stats['planned_rate'] }}</b></div></div><div class="col-4"><div class="border rounded p-3"><div class="small text-muted">Занято</div><b>{{ $stats['occupied_rate'] }}</b></div></div><div class="col-4"><div class="border rounded p-3"><div class="small text-muted">Вакантно</div><b class="text-primary">{{ $stats['vacant_rate'] }}</b></div></div></div>@forelse($staffing as $row)<div class="d-flex justify-content-between border-bottom py-2"><div><div class="fw-semibold">{{ $row->position?->name }}</div><div class="small text-muted">{{ $row->activeAssignments->pluck('user.full_name')->filter()->join(', ') ?: 'Вакансия' }}</div></div><div class="text-end"><div>{{ $row->activeAssignments->sum(fn($a)=>(float)$a->rate) }} / {{ $row->planned_rate }}</div></div></div>@empty<div class="text-muted">Штатные позиции не заведены</div>@endforelse</div></div></div>
</div>

<div class="row g-4 mt-1">
<div class="col-xl-8"><div class="card border-0 shadow-sm"><div class="card-header bg-white"><b>Текущие задачи подразделения</b></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Задача</th><th>Исполнитель</th><th>Срок</th><th>Статус</th><th></th></tr></thead><tbody>@forelse($tasks->take(30) as $t)<tr class="{{ $t->is_overdue?'table-danger':'' }}"><td><b>{{ $t->title }}</b><div class="small text-muted">{{ $t->progress }}%</div></td><td>{{ $t->assignee?->full_name }}</td><td>{{ $t->due_at?->format('d.m.Y H:i') ?? '—' }}</td><td>@if($t->is_overdue)<span class="badge text-bg-danger">Просрочено</span>@elseif($t->status==='review')<span class="badge text-bg-warning">На проверке</span>@else<span class="badge text-bg-light border">{{ $t->status==='in_progress'?'В работе':'Новая' }}</span>@endif</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="{{ route('tasks.page',['task'=>$t->id]) }}">Открыть</a></td></tr>@empty<tr><td colspan="5" class="text-center py-4 text-muted">Открытых задач нет</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-xl-4"><div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white"><b>Отсутствуют сегодня</b></div><div class="list-group list-group-flush">@forelse($absences as $a)<div class="list-group-item"><b>{{ $a->user?->full_name }}</b><div class="small text-muted">{{ ['vacation'=>'Отпуск','sick_leave'=>'Больничный','business_trip'=>'Командировка','training'=>'Обучение','other'=>'Другое'][$a->type] ?? $a->type }} · до {{ $a->date_to->format('d.m.Y') }}</div></div>@empty<div class="p-4 text-center text-muted">Все на месте</div>@endforelse</div></div>
@if($children->count())<div class="card border-0 shadow-sm"><div class="card-header bg-white"><b>Дочерние подразделения</b></div><div class="list-group list-group-flush">@foreach($children as $child)<a href="{{ route('departments.show360',$child) }}" class="list-group-item list-group-item-action d-flex justify-content-between"><span>{{ $child->name }}</span><i class="bi bi-chevron-right"></i></a>@endforeach</div></div>@endif
</div>
</div>
@endsection