@extends('layouts.app')
@section('title','Подразделения — CRM ЗЦРБ')
@section('header','Подразделения')
@section('content')
<div class="d-flex mb-3">@if(auth()->user()->isManager())<button class="btn btn-primary ms-auto" data-bs-toggle="modal" data-bs-target="#departmentModal" onclick="newDepartment()"><i class="bi bi-plus-lg me-1"></i>Добавить подразделение</button>@endif</div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Название</th><th>Кратко</th><th>Тип</th><th>Родитель</th><th>Сотрудников</th><th>Статус</th><th></th></tr></thead><tbody id="departmentRows"><tr><td colspan="7" class="text-center py-4">Загрузка...</td></tr></tbody></table></div></div>
@if(auth()->user()->isManager())
<div class="modal fade" id="departmentModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="departmentForm"><div class="modal-header"><h5 class="modal-title">Подразделение</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="department_id"><div class="mb-3"><label class="form-label">Название</label><input name="name" class="form-control" required></div><div class="mb-3"><label class="form-label">Краткое название</label><input name="short_name" class="form-control"></div><div class="mb-3"><label class="form-label">Тип</label><select name="type" class="form-select" required><option value="department">Отделение</option><option value="administration">Администрация</option><option value="service">Служба</option><option value="office">Кабинет</option><option value="other">Другое</option></select></div><div class="mb-3"><label class="form-label">Родитель</label><select name="parent_id" id="parent_id" class="form-select"><option value="">— верхний уровень —</option></select></div><div class="mb-3"><label class="form-label">Порядок</label><input type="number" min="0" name="sort_order" class="form-control" value="0"></div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="department_active" checked><label class="form-check-label">Активно</label></div><div id="depError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Сохранить</button></div></form></div></div>
@endif
@endsection
@push('scripts')
<script>
let deps=[];function e(v){return $('<div>').text(v??'').html()}function depName(id){return deps.find(x=>x.id==id)?.name||'—'}function typeName(v){return {administration:'Администрация',department:'Отделение',service:'Служба',office:'Кабинет',other:'Другое'}[v]||v}
function loadDeps(){$.get('{{ route('departments.index') }}',r=>{deps=r;let h='';r.forEach(d=>h+=`<tr><td><strong>${e(d.name)}</strong></td><td>${e(d.short_name||'')}</td><td>${e(typeName(d.type))}</td><td>${e(depName(d.parent_id))}</td><td>${d.users_count}</td><td>${d.is_active?'<span class="badge text-bg-success">Активно</span>':'<span class="badge text-bg-secondary">Отключено</span>'}</td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="{{ url('/departments') }}/${d.id}/360" title="360°"><i class="bi bi-speedometer2"></i></a> @if(auth()->user()->isManager())<button class="btn btn-sm btn-outline-primary" onclick="editDepartment(${d.id})"><i class="bi bi-pencil"></i></button>@endif</td></tr>`);$('#departmentRows').html(h||'<tr><td colspan="7" class="text-center py-4 text-muted">Нет подразделений</td></tr>');let o='<option value="">— верхний уровень —</option>';r.forEach(d=>o+=`<option value="${d.id}">${e(d.name)}</option>`);$('#parent_id').html(o)})}
function newDepartment(){$('#departmentForm')[0].reset();$('#department_id').val('');$('#department_active').prop('checked',true);$('#depError').addClass('d-none')}
function editDepartment(id){let d=deps.find(x=>x.id==id);newDepartment();$('#department_id').val(id);for(let k of ['name','short_name','type','parent_id','sort_order'])$(`[name=${k}]`).val(d[k]??'');$('#department_active').prop('checked',!!d.is_active);bootstrap.Modal.getOrCreateInstance(document.getElementById('departmentModal')).show()}
$('#departmentForm').on('submit',function(x){x.preventDefault();let id=$('#department_id').val(),data=Object.fromEntries(new FormData(this).entries());data.is_active=$('#department_active').is(':checked')?1:0;$.ajax({url:id?'{{ url('/ajax/departments') }}/'+id:'{{ route('departments.store') }}',method:id?'PATCH':'POST',data}).done(()=>{bootstrap.Modal.getInstance(document.getElementById('departmentModal')).hide();loadDeps()}).fail(r=>$('#depError').removeClass('d-none').text(r.responseJSON?.message||'Ошибка сохранения'))});loadDeps();
</script>
@endpush
