@extends('layouts.app')
@section('title','Совещания — CRM ЗЦРБ')
@section('header','Совещания и протоколы')
@section('content')
<div class="d-flex gap-2 flex-wrap mb-3">
  <input id="meetingQ" class="form-control" style="max-width:300px" placeholder="Поиск совещаний">
  <select id="meetingStatus" class="form-select" style="max-width:180px"><option value="">Все статусы</option><option value="draft">Черновик</option><option value="active">В работе</option><option value="closed">Закрыт</option></select>
  <button class="btn btn-primary ms-auto" data-bs-toggle="modal" data-bs-target="#meetingModal" onclick="newMeeting()"><i class="bi bi-people me-1"></i>Новое совещание</button>
</div>
<div id="meetingList" class="row g-3"></div>

<div class="modal fade" id="meetingModal" tabindex="-1"><div class="modal-dialog modal-lg"><form id="meetingForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Совещание</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">Название</label><input name="title" class="form-control" required></div><div class="col-md-4"><label class="form-label">Дата и время</label><input name="held_at" type="datetime-local" class="form-control" required></div><div class="col-md-6"><label class="form-label">Место</label><input name="location" class="form-control"></div><div class="col-md-3"><label class="form-label">Председатель</label><select name="chairman_id" class="form-select"><option value="">—</option>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Секретарь</label><select name="secretary_id" class="form-select"><option value="">—</option>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Участники</label><select name="participants[]" class="form-select" multiple size="6">@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select><div class="form-text">Ctrl/⌘ для выбора нескольких сотрудников.</div></div><div class="col-12"><label class="form-label">Заметки / повестка</label><textarea name="notes" class="form-control" rows="4"></textarea></div><div class="col-md-4"><label class="form-label">Статус</label><select name="status" class="form-select"><option value="draft">Черновик</option><option value="active" selected>В работе</option><option value="closed">Закрыт</option></select></div></div><div id="meetingError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Сохранить</button></div></form></div></div>

<div class="modal fade" id="protocolModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><h5 id="protocolTitle" class="modal-title"></h5><div id="protocolMeta" class="small text-muted"></div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div id="protocolStats" class="row g-2 mb-4"></div><div id="protocolNotes" class="mb-4"></div><div class="d-flex align-items-center mb-2"><h6 class="mb-0">Поручения протокола</h6><button id="btnAddItem" class="btn btn-sm btn-primary ms-auto" data-bs-toggle="collapse" data-bs-target="#newItemBox"><i class="bi bi-plus-lg me-1"></i>Добавить поручение</button></div><div class="collapse mb-3" id="newItemBox"><div class="card card-body bg-light border"><div class="row g-2"><div class="col-12"><label class="form-label">Поручение</label><textarea id="itemInstruction" class="form-control" rows="3"></textarea></div><div class="col-md-5"><label class="form-label">Исполнитель</label><select id="itemAssignee" class="form-select">@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Срок</label><input id="itemDueAt" type="datetime-local" class="form-control"></div><div class="col-md-2"><label class="form-label">Приоритет</label><select id="itemPriority" class="form-select"><option value="normal">Обычный</option><option value="high">Высокий</option><option value="critical">Критический</option><option value="low">Низкий</option></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100" onclick="addProtocolItem()">Создать</button></div></div></div></div><div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th>№</th><th>Поручение</th><th>Исполнитель</th><th>Срок</th><th>Статус</th><th style="width:150px">Прогресс</th><th></th></tr></thead><tbody id="protocolRows"></tbody></table></div></div><div class="modal-footer"><button id="btnCloseMeeting" class="btn btn-outline-danger me-auto" onclick="closeMeeting()"><i class="bi bi-lock me-1"></i>Закрыть протокол</button><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть окно</button></div></div></div></div>
@endsection
@push('scripts')
<script>
let currentMeeting=null;function escM(v){return $('<div>').text(v??'').html()}function ms(s){return {draft:'Черновик',active:'В работе',closed:'Закрыт'}[s]||s}function ts(s){return {new:'Новая',in_progress:'В работе',review:'На проверке',completed:'Выполнено',cancelled:'Отменено'}[s]||s}
function loadMeetings(){ $.get('{{ route('meetings.index') }}',{q:$('#meetingQ').val(),status:$('#meetingStatus').val()},r=>{let h='';r.data.forEach(m=>{const items=m.items||[],done=items.filter(x=>x.task?.status==='completed').length,over=items.filter(x=>x.task?.is_overdue).length,review=items.filter(x=>x.task?.status==='review').length,p=items.length?Math.round(done/items.length*100):0;h+=`<div class="col-12"><div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex gap-3 flex-wrap"><div class="flex-grow-1"><h5 class="mb-1">${escM(m.title)}</h5><div class="text-muted small">${new Date(m.held_at).toLocaleString('ru-RU')}${m.location?' · '+escM(m.location):''}</div></div><span class="badge text-bg-${m.status==='closed'?'secondary':m.status==='active'?'primary':'light'} border">${ms(m.status)}</span></div><div class="d-flex gap-3 flex-wrap mt-3 small"><span>Поручений: <b>${items.length}</b></span><span class="text-success">Выполнено: <b>${done}</b></span><span class="text-warning">На проверке: <b>${review}</b></span><span class="text-danger">Просрочено: <b>${over}</b></span></div><div class="d-flex align-items-center gap-2 mt-3"><div class="progress flex-grow-1" style="height:8px"><div class="progress-bar" style="width:${p}%"></div></div><span class="small">${p}%</span><button class="btn btn-sm btn-outline-primary ms-2" onclick="openMeeting(${m.id})">Открыть протокол</button></div></div></div></div>`});$('#meetingList').html(h||'<div class="col-12"><div class="alert alert-light border text-center">Совещаний пока нет</div></div>')})}
function newMeeting(){$('#meetingForm')[0].reset();$('#meetingForm [name=status]').val('active');$('#meetingError').addClass('d-none')}
$('#meetingForm').on('submit',function(e){e.preventDefault();const fd=new FormData(this),d={participants:[]};for(const [k,v] of fd.entries()){if(k==='participants[]')d.participants.push(v);else d[k]=v}$.post('{{ route('meetings.store') }}',d).done(()=>{bootstrap.Modal.getInstance(document.getElementById('meetingModal')).hide();loadMeetings()}).fail(x=>$('#meetingError').removeClass('d-none').text(x.responseJSON?.message||'Ошибка сохранения'))});
function openMeeting(id){$.get(`{{ url('/ajax/meetings') }}/${id}`,m=>{currentMeeting=m;$('#protocolTitle').text(m.title);$('#protocolMeta').text(`${new Date(m.held_at).toLocaleString('ru-RU')}${m.location?' · '+m.location:''}${m.chairman?' · председатель '+m.chairman.last_name+' '+m.chairman.first_name:''}`);$('#protocolNotes').html(m.notes?`<div class="alert alert-light border"><b>Повестка / заметки:</b><div class="mt-1">${escM(m.notes)}</div></div>`:'');renderProtocol(m);$('#btnAddItem').toggle(m.status!=='closed');$('#btnCloseMeeting').toggle(m.status!=='closed');bootstrap.Modal.getOrCreateInstance(document.getElementById('protocolModal')).show()})}
function renderProtocol(m){const items=m.items||[],done=items.filter(x=>x.task?.status==='completed').length,over=items.filter(x=>x.task?.is_overdue).length,review=items.filter(x=>x.task?.status==='review').length;$('#protocolStats').html(`<div class="col-6 col-md-3"><div class="border rounded p-3"><div class="text-muted small">Поручений</div><div class="fs-4 fw-bold">${items.length}</div></div></div><div class="col-6 col-md-3"><div class="border rounded p-3"><div class="text-muted small">Выполнено</div><div class="fs-4 fw-bold text-success">${done}</div></div></div><div class="col-6 col-md-3"><div class="border rounded p-3"><div class="text-muted small">На проверке</div><div class="fs-4 fw-bold text-warning">${review}</div></div></div><div class="col-6 col-md-3"><div class="border rounded p-3"><div class="text-muted small">Просрочено</div><div class="fs-4 fw-bold text-danger">${over}</div></div></div>`);let h='';items.forEach(i=>{const t=i.task||{},overdue=t.is_overdue,progress=t.progress||0;h+=`<tr class="${overdue?'table-danger':''}"><td>${i.number}</td><td>${escM(i.instruction)}</td><td><b>${escM((i.assignee?.last_name||'')+' '+(i.assignee?.first_name||''))}</b><div class="small text-muted">${escM(i.assignee?.department?.name||'')}</div></td><td class="text-nowrap">${i.due_at?new Date(i.due_at).toLocaleString('ru-RU'):'—'}</td><td>${overdue?'<span class="badge text-bg-danger">Просрочено</span>':`<span class="badge text-bg-light border">${ts(t.status||'new')}</span>`}</td><td><div class="progress" style="height:18px"><div class="progress-bar" style="width:${progress}%">${progress}%</div></div></td><td class="text-end">${t.id?`<a class="btn btn-sm btn-outline-primary" href="{{ url('/tasks') }}?task=${t.id}">Задача</a>`:''}</td></tr>`});$('#protocolRows').html(h||'<tr><td colspan="7" class="text-center text-muted py-4">Поручений ещё нет</td></tr>')}
function addProtocolItem(){if(!currentMeeting)return;const instruction=$('#itemInstruction').val().trim();if(!instruction){alert('Введите поручение');return}$.post(`{{ url('/ajax/meetings') }}/${currentMeeting.id}/items`,{instruction,assigned_to:$('#itemAssignee').val(),due_at:$('#itemDueAt').val(),priority:$('#itemPriority').val()}).done(()=>{$('#itemInstruction').val('');$('#itemDueAt').val('');openMeeting(currentMeeting.id);loadMeetings()}).fail(x=>alert(x.responseJSON?.message||'Ошибка создания поручения'))}
function closeMeeting(){if(!currentMeeting||!confirm('Закрыть протокол? Новые поручения после этого добавлять нельзя.'))return;$.post(`{{ url('/ajax/meetings') }}/${currentMeeting.id}/close`).done(()=>{openMeeting(currentMeeting.id);loadMeetings()}).fail(x=>alert(x.responseJSON?.message||'Ошибка'))}
$('#meetingQ').on('input',()=>{clearTimeout(window.meetT);window.meetT=setTimeout(loadMeetings,300)});$('#meetingStatus').on('change',loadMeetings);loadMeetings();
</script>
@endpush
