@extends('layouts.app')
@section('title','Аттестация — CRM')
@section('header','Аттестация')

@push('styles')
<style>
.score-card{border:1px solid #e5e7eb;border-radius:14px}.score-options{display:grid;grid-template-columns:repeat(4,minmax(80px,1fr));gap:8px}.score-choice{border:1px solid #dee2e6;border-radius:10px;padding:10px;text-align:center;cursor:pointer}.score-choice input{margin-right:5px}.department-title{position:sticky;top:58px;z-index:4;background:#eef3f8;border-radius:10px;padding:9px 12px;margin:18px 0 10px;font-weight:700}.matrix-wrap{overflow:auto;max-height:70vh}.matrix-table{white-space:nowrap}.matrix-table th,.matrix-table td{text-align:center;vertical-align:middle}.matrix-table .person{text-align:left;position:sticky;left:0;background:#fff;z-index:2;min-width:250px}.matrix-table thead th{position:sticky;top:0;background:#ffc107;z-index:3}.matrix-table thead .person{z-index:4}.score-1{background:#f8d7da!important}.score-2{background:#fff3cd!important}.score-3{background:#cff4fc!important}.score-4{background:#d1e7dd!important}.legend-box{width:18px;height:18px;border-radius:4px;display:inline-block;vertical-align:middle;margin-right:5px}.section-badge{font-size:.8rem}.commission-card{border-left:4px solid #6f42c1}.relation-card{border-left:4px solid #0d6efd}@media(max-width:767px){.score-options{grid-template-columns:repeat(2,1fr)}.matrix-table .person{min-width:190px}}
</style>
@endpush

@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif

<div class="row g-3">
<div class="col-xl-3"><div class="card border-0 shadow-sm"><div class="card-header bg-white d-flex align-items-center"><b>Периоды аттестации</b>@if(auth()->user()->isManager())<button class="btn btn-sm btn-primary ms-auto" data-bs-toggle="modal" data-bs-target="#createCampaign"><i class="bi bi-plus-lg"></i></button>@endif</div><div class="list-group list-group-flush">@forelse($campaigns as $c)<a class="list-group-item list-group-item-action {{ $selected && $selected->id==$c->id?'active':'' }}" href="{{ route('attestation.page',['campaign'=>$c->id]) }}"><div class="fw-semibold">{{ $c->title }}</div><div class="small {{ $selected && $selected->id==$c->id?'text-white-50':'text-muted' }}">{{ $c->starts_at ?: 'без даты' }} — {{ $c->ends_at ?: 'без даты' }}</div></a>@empty<div class="p-3 text-muted">Аттестаций пока нет.</div>@endforelse</div></div></div>

<div class="col-xl-9">
@if($selected)
<div class="card border-0 shadow-sm mb-3"><div class="card-body"><div class="d-flex flex-wrap align-items-center gap-2"><div><h4 class="mb-1">{{ $selected->title }}</h4><div class="text-muted">{{ $selected->description }}</div></div><span class="badge {{ $selected->is_active?'text-bg-success':'text-bg-secondary' }} ms-auto">{{ $selected->is_active?'Активна':'Закрыта' }}</span></div><hr><div class="d-flex flex-wrap gap-3 small"><span><span class="legend-box score-1"></span><b>1</b> — связи нет</span><span><span class="legend-box score-2"></span><b>2</b> — связь есть, но плохая</span><span><span class="legend-box score-3"></span><b>3</b> — средняя</span><span><span class="legend-box score-4"></span><b>4</b> — хорошая</span></div>@if($commissionMembers->count())<div class="mt-3 small"><b>Аттестационная комиссия:</b> {{ $commissionMembers->pluck('full_name')->join(', ') }}</div>@endif</div></div>

@if($myDepartment && $colleagues->count())
<div class="card border-0 shadow-sm mb-3 relation-card"><div class="card-header bg-white"><div class="d-flex align-items-center"><b>1. Оценка рабочих связей сотрудниками</b><span class="badge text-bg-primary ms-2 section-badge">сотрудники</span></div><div class="small text-muted">Оценивайте сотрудников своего и других подразделений, с которыми работаете. Себя оценивать нельзя.</div></div><div class="card-body"><form method="POST" action="{{ route('attestation.scores.save',$selected->id) }}">@csrf
@foreach($colleagues->groupBy(fn($p)=>$p->department?->name ?: 'Без подразделения') as $departmentName=>$people)<div class="department-title"><i class="bi bi-diagram-3 me-2"></i>{{ $departmentName }} <span class="badge text-bg-light border ms-1">{{ $people->count() }}</span></div>@foreach($people as $person)<div class="score-card p-3 mb-3"><div class="d-flex flex-wrap align-items-center gap-2 mb-2"><div><div class="fw-semibold">{{ $person->full_name }}</div><div class="small text-muted">{{ $person->position ?: 'Должность не указана' }} · {{ $person->department?->name ?: 'Без подразделения' }}</div></div>@if(isset($myScores[$person->id]))<span class="badge text-bg-light border ms-auto">Текущая: {{ $myScores[$person->id] }}</span>@endif</div><div class="score-options">@foreach([1=>'Связи нет',2=>'Плохая',3=>'Средняя',4=>'Хорошая'] as $score=>$label)<label class="score-choice score-{{ $score }}"><input type="radio" name="scores[{{ $person->id }}]" value="{{ $score }}" {{ (int)($myScores[$person->id]??0)===$score?'checked':'' }}><b>{{ $score }}</b> — {{ $label }}</label>@endforeach</div></div>@endforeach @endforeach
<button class="btn btn-primary"><i class="bi bi-check2-circle me-1"></i>Сохранить оценки связей</button></form></div></div>
@endif

@if($isCommissionMember && $commissionTargets->count())
<div class="card border-0 shadow-sm mb-3 commission-card"><div class="card-header bg-white"><div class="d-flex align-items-center"><b>2. Оценка аттестационной комиссии</b><span class="badge ms-2 section-badge" style="background:#6f42c1">комиссия</span></div><div class="small text-muted">Вы включены в состав комиссии. Выставьте свою оценку по каждому аттестуемому сотруднику. Результат каждого члена комиссии хранится отдельно.</div></div><div class="card-body"><form method="POST" action="{{ route('attestation.commission-scores.save',$selected->id) }}">@csrf
@foreach($commissionTargets->groupBy(fn($p)=>$p->department?->name ?: 'Без подразделения') as $departmentName=>$people)<div class="department-title"><i class="bi bi-people-fill me-2"></i>{{ $departmentName }} <span class="badge text-bg-light border ms-1">{{ $people->count() }}</span></div>@foreach($people as $person)<div class="score-card p-3 mb-3"><div class="d-flex flex-wrap align-items-center gap-2 mb-2"><div><div class="fw-semibold">{{ $person->full_name }}</div><div class="small text-muted">{{ $person->position ?: 'Должность не указана' }}</div></div>@if(isset($myCommissionScores[$person->id]))<span class="badge text-bg-light border ms-auto">Моя оценка: {{ $myCommissionScores[$person->id] }}</span>@endif</div><div class="score-options">@foreach([1=>'1',2=>'2',3=>'3',4=>'4'] as $score=>$label)<label class="score-choice score-{{ $score }}"><input type="radio" name="scores[{{ $person->id }}]" value="{{ $score }}" {{ (int)($myCommissionScores[$person->id]??0)===$score?'checked':'' }}><b>{{ $label }}</b></label>@endforeach</div></div>@endforeach @endforeach
<button class="btn text-white" style="background:#6f42c1"><i class="bi bi-check2-circle me-1"></i>Сохранить оценки комиссии</button></form></div></div>
@endif

@if(auth()->user()->isManager() && $analytics)
<div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white d-flex flex-wrap align-items-center gap-2"><div><b>Свод рабочих связей</b><div class="small text-muted">Оценки от сотрудников всей организации.</div></div><form class="ms-auto d-flex gap-2" method="GET"><input type="hidden" name="campaign" value="{{ $selected->id }}"><select class="form-select form-select-sm" name="department" onchange="this.form.submit()">@foreach($departments as $d)<option value="{{ $d->id }}" {{ (int)$analytics['department_id']===(int)$d->id?'selected':'' }}>{{ $d->name }}</option>@endforeach</select></form></div><div class="card-body"><div class="matrix-wrap border rounded"><table class="table table-bordered table-sm mb-0 matrix-table"><thead><tr><th class="person">ФИО / специальность</th><th>СРЕД</th><th>Кол.</th><th>Сумма</th>@foreach($analytics['evaluators'] as $e)<th title="{{ $e->full_name }} · {{ $e->department?->name }}">{{ $e->id }}</th>@endforeach</tr></thead><tbody>@foreach($analytics['rows'] as $row)<tr><td class="person"><div class="fw-semibold">{{ $row['user']->full_name }}</div><div class="small text-muted">{{ $row['user']->position }}</div></td><td class="fw-bold">{{ $row['avg'] ?? '—' }}</td><td>{{ $row['count'] }}</td><td>{{ $row['sum'] }}</td>@foreach($analytics['evaluators'] as $e)@php($v=$row['scores'][$e->id]??null)<td class="{{ $v?'score-'.$v:'' }}">{{ $v??'' }}</td>@endforeach</tr>@endforeach</tbody></table></div></div></div>
@endif

@if(auth()->user()->isManager() && $commissionAnalytics)
<div class="card border-0 shadow-sm mb-3 commission-card"><div class="card-header bg-white"><div class="d-flex flex-wrap align-items-center gap-2"><div><b>Свод аттестационной комиссии</b><div class="small text-muted">Формат повторяет предоставленную таблицу: индекс, ФИО, специальность, среднее, количество, сумма и оценки членов комиссии.</div></div><span class="badge ms-auto" style="background:#6f42c1">Комиссия</span></div></div><div class="card-body"><div class="matrix-wrap border rounded"><table class="table table-bordered table-sm mb-0 matrix-table"><thead><tr><th>Индекс</th><th class="person">ФИО</th><th>Специальность</th><th>СРЕД</th><th>Кол.</th><th>Сумма</th>@foreach($commissionAnalytics['members'] as $m)<th title="{{ $m->full_name }} · {{ $m->position }}">{{ $m->id }}</th>@endforeach</tr></thead><tbody>@foreach($commissionAnalytics['rows'] as $row)<tr><td class="fw-semibold">{{ $row['user']->id }}</td><td class="person"><div class="fw-semibold">{{ $row['user']->full_name }}</div></td><td class="text-start">{{ $row['user']->position ?: '—' }}</td><td class="fw-bold">{{ $row['avg'] ?? '—' }}</td><td>{{ $row['count'] }}</td><td>{{ $row['sum'] }}</td>@foreach($commissionAnalytics['members'] as $m)@php($v=$row['scores'][$m->id]??null)<td class="{{ $v?'score-'.$v:'' }}">{{ $v??'' }}</td>@endforeach</tr>@endforeach</tbody></table></div><div class="small text-muted mt-2">Числа в заголовках справа — ID членов комиссии. Наведите мышь, чтобы увидеть ФИО и должность. Пустая ячейка — член комиссии ещё не оценил сотрудника.</div></div></div>
@endif

@else<div class="alert alert-info">Создайте первую аттестацию.</div>@endif
</div></div>

@if(auth()->user()->isManager())
<div class="modal fade" id="createCampaign" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><form method="POST" action="{{ route('attestation.campaigns.store') }}">@csrf<div class="modal-header"><h5 class="modal-title">Новая аттестация</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label">Название</label><input class="form-control" name="title" value="Аттестация персонала" required></div><div class="mb-3"><label class="form-label">Описание</label><textarea class="form-control" name="description" rows="2">Оценка рабочих связей сотрудниками и отдельная оценка аттестационной комиссии.</textarea></div><div class="row g-2 mb-3"><div class="col-md-6"><label class="form-label">Начало</label><input type="date" class="form-control" name="starts_at"></div><div class="col-md-6"><label class="form-label">Окончание</label><input type="date" class="form-control" name="ends_at"></div></div><div class="row g-4"><div class="col-lg-6"><h6>Подразделения, сотрудники которых проходят аттестацию</h6><div class="border rounded p-3" style="max-height:360px;overflow:auto">@foreach($departments as $d)<label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="department_ids[]" value="{{ $d->id }}"><span class="form-check-label">{{ $d->name }}</span></label>@endforeach</div></div><div class="col-lg-6"><h6>Состав аттестационной комиссии</h6><div class="small text-muted mb-2">Выберите сотрудников, которые будут выставлять комиссионную оценку каждому человеку.</div><div class="border rounded p-3" style="max-height:360px;overflow:auto">@foreach($allUsers->groupBy(fn($u)=>$u->department?->name ?: 'Без подразделения') as $departmentName=>$users)<div class="fw-semibold mt-2 mb-1">{{ $departmentName }}</div>@foreach($users as $u)<label class="form-check mb-2"><input class="form-check-input" type="checkbox" name="commission_member_ids[]" value="{{ $u->id }}"><span class="form-check-label">{{ $u->full_name }} <span class="text-muted">{{ $u->position ? '— '.$u->position : '' }}</span></span></label>@endforeach @endforeach</div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Создать аттестацию</button></div></form></div></div></div>
@endif
@endsection
