@extends('layouts.app')
@section('title','Аналитика сотрудников — CRM')
@section('header','Аналитика сотрудников')
@section('content')
@include('analytics._nav')
<div class="row g-3 mb-3">@foreach([['Всего',$kpi['all']],['Активные',$kpi['active']],['Отключены',$kpi['inactive']],['Подразделения',$kpi['departments']],['Руководители',$kpi['managers']]] as $x)<div class="col-6 col-xl"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="small text-muted">{{ $x[0] }}</div><div class="fs-2 fw-semibold">{{ $x[1] }}</div></div></div></div>@endforeach</div>
<div class="row g-3 mb-3"><div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white"><b>Распределение по ролям</b></div><div class="card-body"><canvas data-height="300" data-crm-chart="donut" data-chart='@json(["labels"=>$roles->keys()->map(fn($r)=>["admin"=>"Администратор","manager"=>"Руководитель","hr"=>"Отдел кадров","employee"=>"Сотрудник"][$r]??$r)->values(),"values"=>$roles->values()])'></canvas></div></div></div><div class="col-xl-6"><div class="card border-0 shadow-sm h-100"><div class="card-header bg-white"><b>Численность подразделений</b></div><div class="card-body"><canvas data-height="300" data-crm-chart="bar" data-chart='@json(["labels"=>$departmentRows->pluck("name"),"values"=>$departmentRows->pluck("all")])'></canvas></div></div></div></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white"><b>Приём сотрудников за 12 месяцев</b></div><div class="card-body"><canvas data-height="280" data-crm-chart="line" data-chart='@json(["labels"=>collect($months)->pluck("label"),"series"=>[["label"=>"Принято","values"=>$hires]]])'></canvas></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-white"><b>Подразделения</b></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Подразделение</th><th>Всего</th><th>Активные</th><th>Руководители</th></tr></thead><tbody>@foreach($departmentRows as $r)<tr><td><b>{{ $r['name'] }}</b></td><td>{{ $r['all'] }}</td><td>{{ $r['active'] }}</td><td>{{ $r['managers'] }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
@push('scripts')<script src="/js/crm-charts.js"></script>@endpush
