@extends('layouts.app')
@section('title','Штатное расписание — CRM ЗЦРБ')
@section('header','Штатное расписание')
@section('content')
<ul class="nav nav-tabs mb-3" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="tab" data-bs-target="#staffTab">Штатное расписание</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#positionTab">Справочник должностей</button></li></ul>
<div class="tab-content">
<div class="tab-pane fade show active" id="staffTab">
<div class="d-flex gap-2 mb-3 flex-wrap"><select id="depFilter" class="form-select" style="max-width:300px"><option value="">Все подразделения</option>@foreach($departments as $d)<option value="{{ $d->id }}">{{ $d->name }}</option>@endforeach</select><div class="form-check align-self-center"><input class="form-check-input" type="checkbox" id="vacantOnly"><label class="form-check-label">Только вакансии</label></div><button class="btn btn-primary ms-auto" data-bs-toggle="modal" data-bs-target="#rowModal" onclick="newRow()"><i class="bi bi-plus-lg me-1"></i>Добавить строку</button></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Подразделение</th><th>Должность</th><th>План ставок</th><th>Занято</th><th>Вакантно</th><th>Сотрудники</th><th></th></tr></thead><tbody id="staffRows"><tr><td colspan="7" class="text-center py-4">Загрузка...</td></tr></tbody></table></div></div>
</div>
<div class="tab-pane fade" id="positionTab"><div class="d-flex mb-3"><button class="btn btn-primary ms-auto" data-bs-toggle="modal" data-bs-target="#positionModal" onclick="newPosition()"><i class="bi bi-plus-lg me-1"></i>Добавить должность</button></div><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Должность</th><th>Категория</th><th>Код</th><th>Статус</th><th></th></tr></thead><tbody id="positionRows"></tbody></table></div></div></div></div>

<div class="modal fade" id="rowModal"><div class="modal-dialog"><form id="rowForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Строка штатного расписания</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="row_id"><div class="mb-3"><label class="form-label">Подразделение</label><select name="department_id" class="form-select" required>@foreach($departments as $d)<option value="{{ $d->id }}">{{ $d->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Должность</label><select name="position_id" class="form-select" required>@foreach($positions as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Количество ставок</label><input name="planned_rate" type="number" step="0.01" min="0.01" value="1" class="form-control" required></div><div class="mb-3"><label class="form-label">Примечание</label><input name="note" class="form-control"></div><div class="form-check form-switch"><input id="rowActive" class="form-check-input" type="checkbox" checked><label class="form-check-label">Активно</label></div><div id="rowError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Сохранить</button></div></form></div></div>
<div class="modal fade" id="positionModal"><div class="modal-dialog"><form id="positionForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Должность</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="position_id"><div class="mb-3"><label class="form-label">Название</label><input name="name" class="form-control" required></div><div class="mb-3"><label class="form-label">Категория</label><input name="category" class="form-control" placeholder="Врачебный персонал, средний медперсонал, ИТ..."></div><div class="mb-3"><label class="form-label">Код</label><input name="code" class="form-control"></div><div class="form-check form-switch"><input id="positionActive" class="form-check-input" type="checkbox" checked><label class="form-check-label">Активна</label></div><div id="positionError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Сохранить</button></div></form></div></div>
<div class="modal fade" id="assignModal"><div class="modal-dialog"><form id="assignForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Назначить сотрудника</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="staffing_position_id" id="assignRowId"><div class="mb-3"><label class="form-label">Сотрудник</label><select name="user_id" class="form-select" required>@foreach($employees as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select></div><div class="row g-3"><div class="col-6"><label class="form-label">Ставка</label><input name="rate" type="number" step="0.01" min="0.01" value="1" class="form-control" required></div><div class="col-6"><label class="form-label">Дата начала</label><input name="started_at" type="date" value="{{ now()->format('Y-m-d') }}" class="form-control" required></div><div class="col-12"><label class="form-label">№ приказа</label><input name="order_number" class="form-control"></div><div class="col-12"><label class="form-label">Примечание</label><textarea name="note" class="form-control" rows="2"></textarea></div></div><div class="form-check form-switch mt-3"><input id="assignPrimary" class="form-check-input" type="checkbox"><label class="form-check-label">Основная должность</label></div><div id="assignError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button class="btn btn-light" type="button" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Назначить</button></div></form></div></div>
@endsection
@push('scripts')
<script>
let rowsCache={},positionsCache={};function e(v){return $('<div>').text(v??'').html()}function fmt(v){return Number(v||0).toFixed(2)}
function loadRows(){$.get('{{ route('staffing.rows') }}',{department_id:$('#depFilter').val(),vacant:$('#vacantOnly').is(':checked')?1:0},r=>{rowsCache={};let h='';r.forEach(x=>{rowsCache[x.id]=x;let staff=(x.active_assignments||[]).map(a=>`<div class="d-flex align-items-center gap-1 mb-1"><a href="{{ url('/employees') }}/${a.user.id}">${e(a.user.last_name+' '+a.user.first_name)}</a><span>— ${fmt(a.rate)} ст.</span>${a.is_primary?'<span class="badge text-bg-primary">осн.</span>':''}<button class="btn btn-sm btn-link text-danger p-0 ms-1" onclick="endAssignment(${a.id})" title="Закрыть назначение"><i class="bi bi-x-circle"></i></button></div>`).join('')||'<span class="text-muted">нет</span>';h+=`<tr><td>${e(x.department?.name)}</td><td><strong>${e(x.position?.name)}</strong></td><td>${fmt(x.planned_rate)}</td><td>${fmt(x.occupied_rate)}</td><td>${Number(x.vacant_rate)>0?`<span class="badge text-bg-warning">${fmt(x.vacant_rate)}</span>`:'0.00'}</td><td>${staff}</td><td class="text-end"><button class="btn btn-sm btn-outline-success" onclick="assignTo(${x.id})" title="Назначить"><i class="bi bi-person-plus"></i></button> <button class="btn btn-sm btn-outline-primary" onclick="editRow(${x.id})"><i class="bi bi-pencil"></i></button></td></tr>`});$('#staffRows').html(h||'<tr><td colspan="7" class="text-center py-4 text-muted">Нет строк штатного расписания</td></tr>')})}
function loadPositions(){$.get('{{ route('staffing.positions') }}',r=>{positionsCache={};let h='';r.forEach(p=>{positionsCache[p.id]=p;h+=`<tr><td><strong>${e(p.name)}</strong></td><td>${e(p.category||'—')}</td><td>${e(p.code||'—')}</td><td>${p.is_active?'<span class="badge text-bg-success">Активна</span>':'<span class="badge text-bg-secondary">Отключена</span>'}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary" onclick="editPosition(${p.id})"><i class="bi bi-pencil"></i></button></td></tr>`});$('#positionRows').html(h)})}
function newRow(){$('#rowForm')[0].reset();$('#row_id').val('');$('#rowActive').prop('checked',true);$('#rowError').addClass('d-none')}function editRow(id){let x=rowsCache[id];newRow();$('#row_id').val(id);$('[name=department_id]').val(x.department_id);$('[name=position_id]').val(x.position_id);$('[name=planned_rate]').val(x.planned_rate);$('[name=note]').val(x.note||'');$('#rowActive').prop('checked',!!x.is_active);bootstrap.Modal.getOrCreateInstance('#rowModal').show()}
$('#rowForm').on('submit',function(ev){ev.preventDefault();let id=$('#row_id').val(),d=Object.fromEntries(new FormData(this).entries());d.is_active=$('#rowActive').is(':checked')?1:0;$.ajax({url:id?'{{ url('/ajax/staffing/rows') }}/'+id:'{{ route('staffing.rows.store') }}',method:id?'PATCH':'POST',data:d}).done(()=>{bootstrap.Modal.getInstance('#rowModal').hide();loadRows()}).fail(x=>$('#rowError').removeClass('d-none').text(x.responseJSON?.message||'Ошибка'))})
function newPosition(){$('#positionForm')[0].reset();$('#position_id').val('');$('#positionActive').prop('checked',true);$('#positionError').addClass('d-none')}function editPosition(id){let p=positionsCache[id];newPosition();$('#position_id').val(id);$('[name=name]').val(p.name);$('[name=category]').val(p.category||'');$('[name=code]').val(p.code||'');$('#positionActive').prop('checked',!!p.is_active);bootstrap.Modal.getOrCreateInstance('#positionModal').show()}
$('#positionForm').on('submit',function(ev){ev.preventDefault();let id=$('#position_id').val(),d=Object.fromEntries(new FormData(this).entries());d.is_active=$('#positionActive').is(':checked')?1:0;$.ajax({url:id?'{{ url('/ajax/staffing/positions') }}/'+id:'{{ route('staffing.positions.store') }}',method:id?'PATCH':'POST',data:d}).done(()=>{bootstrap.Modal.getInstance('#positionModal').hide();loadPositions();location.reload()}).fail(x=>$('#positionError').removeClass('d-none').text(x.responseJSON?.message||'Ошибка'))})
function assignTo(id){$('#assignForm')[0].reset();$('#assignRowId').val(id);$('[name=started_at]').val('{{ now()->format('Y-m-d') }}');$('#assignError').addClass('d-none');bootstrap.Modal.getOrCreateInstance('#assignModal').show()}
$('#assignForm').on('submit',function(ev){ev.preventDefault();let d=new FormData(this);d.set('is_primary',$('#assignPrimary').is(':checked')?1:0);$.ajax({url:'{{ route('staffing.assignments.store') }}',method:'POST',data:d,processData:false,contentType:false}).done(()=>{bootstrap.Modal.getInstance('#assignModal').hide();loadRows()}).fail(x=>$('#assignError').removeClass('d-none').text(x.responseJSON?.message||'Ошибка назначения'))})
function endAssignment(id){let date=prompt('Дата окончания назначения (ГГГГ-ММ-ДД):',new Date().toISOString().slice(0,10));if(!date)return;$.post(`{{ url('/ajax/staffing/assignments') }}/${id}/end`,{ended_at:date}).done(loadRows).fail(x=>alert(x.responseJSON?.message||'Не удалось закрыть назначение'))}
$('#depFilter,#vacantOnly').on('change',loadRows);loadRows();loadPositions();
</script>
@endpush
