@extends('layouts.app')
@section('title','Планы — CRM ЗЦРБ')
@section('header','Планы')
@section('content')
<div class="d-flex gap-2 mb-3 flex-wrap">
  <input id="q" class="form-control" style="max-width:280px" placeholder="Поиск по планам">
  <select id="statusFilter" class="form-select" style="max-width:190px"><option value="">Все статусы</option><option value="draft">Черновик</option><option value="active">Активный</option><option value="completed">Выполнен</option><option value="cancelled">Отменён</option></select>
  <select id="periodFilter" class="form-select" style="max-width:190px"><option value="">Все периоды</option><option value="day">День</option><option value="week">Неделя</option><option value="month">Месяц</option><option value="quarter">Квартал</option><option value="year">Год</option><option value="custom">Произвольный</option></select>
  @if(auth()->user()->isManager())<select id="userFilter" class="form-select" style="max-width:260px"><option value="">Все сотрудники</option>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select>@endif
  <button class="btn btn-primary ms-auto" data-bs-toggle="modal" data-bs-target="#planModal" onclick="newPlan()"><i class="bi bi-plus-lg me-1"></i>Новый план</button>
</div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>План</th><th>Сотрудник</th><th>Период</th><th>Статус</th><th style="width:180px">Выполнение</th><th></th></tr></thead><tbody id="planRows"><tr><td colspan="6" class="text-center py-4">Загрузка...</td></tr></tbody></table></div></div>

<div class="modal fade" id="planModal" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" id="planForm"><div class="modal-header"><h5 class="modal-title">План</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="plan_id"><div class="row g-3"><div class="col-md-6"><label class="form-label">Сотрудник</label><select name="user_id" class="form-select" required>@foreach($users as $u)<option value="{{ $u->id }}" @selected($u->id===auth()->id())>{{ $u->full_name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Название</label><input name="title" class="form-control" required></div><div class="col-12"><label class="form-label">Описание</label><textarea name="description" class="form-control" rows="3"></textarea></div><div class="col-md-4"><label class="form-label">Тип периода</label><select name="period_type" class="form-select"><option value="day">День</option><option value="week">Неделя</option><option value="month" selected>Месяц</option><option value="quarter">Квартал</option><option value="year">Год</option><option value="custom">Произвольный</option></select></div><div class="col-md-4"><label class="form-label">Начало</label><input type="date" name="period_start" class="form-control" required></div><div class="col-md-4"><label class="form-label">Окончание</label><input type="date" name="period_end" class="form-control" required></div><div class="col-md-4"><label class="form-label">Статус</label><select name="status" class="form-select"><option value="draft">Черновик</option><option value="active" selected>Активный</option><option value="completed">Выполнен</option><option value="cancelled">Отменён</option></select></div></div><div id="planError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Сохранить</button></div></form></div></div>

<div class="modal fade" id="taskModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="taskForm"><div class="modal-header"><h5 class="modal-title">Добавить пункт плана</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="task_plan_id"><div class="mb-3"><label class="form-label">Пункт / задача</label><input name="title" class="form-control" required></div><div class="mb-3"><label class="form-label">Описание</label><textarea name="description" class="form-control" rows="3"></textarea></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Приоритет</label><select name="priority" class="form-select"><option value="normal">Обычный</option><option value="high">Высокий</option><option value="critical">Критический</option><option value="low">Низкий</option></select></div><div class="col-md-6"><label class="form-label">Срок</label><input type="datetime-local" name="due_at" class="form-control"></div></div><div id="taskError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Добавить</button></div></form></div></div>
@endsection
@push('scripts')
<script>
let plans=[]; const esc=v=>$('<div>').text(v??'').html();
const statusName={draft:'Черновик',active:'Активный',completed:'Выполнен',cancelled:'Отменён'};
function params(){let p={q:$('#q').val(),status:$('#statusFilter').val(),period_type:$('#periodFilter').val()}; if($('#userFilter').length)p.user_id=$('#userFilter').val(); return p}
function loadPlans(){$.get('{{ route('plans.index') }}',params(),r=>{plans=r.data;let h='';r.data.forEach(p=>{let taskInfo=(p.tasks||[]).length?`<div class="small text-muted mt-1">Пунктов: ${p.tasks.length}</div>`:'';h+=`<tr><td><strong>${esc(p.title)}</strong><div class="small text-muted">${esc(p.description||'')}</div>${taskInfo}</td><td>${esc(p.user?.full_name||'')}</td><td>${p.period_start} — ${p.period_end}</td><td><span class="badge text-bg-${p.status==='completed'?'success':p.status==='cancelled'?'secondary':p.status==='active'?'primary':'warning'}">${statusName[p.status]||p.status}</span></td><td><div class="progress" style="height:18px"><div class="progress-bar" style="width:${p.progress||0}%">${p.progress||0}%</div></div></td><td class="text-end"><div class="btn-group btn-group-sm"><button class="btn btn-outline-primary" onclick="editPlan(${p.id})"><i class="bi bi-pencil"></i></button><button class="btn btn-outline-success" onclick="addTask(${p.id})"><i class="bi bi-plus-lg"></i></button></div></td></tr>`});$('#planRows').html(h||'<tr><td colspan="6" class="text-center py-4 text-muted">Планы не найдены</td></tr>')})}
function setDefaultDates(){let d=new Date(),s=new Date(d.getFullYear(),d.getMonth(),1),e=new Date(d.getFullYear(),d.getMonth()+1,0),f=x=>x.toISOString().slice(0,10);$('[name=period_start]').val(f(s));$('[name=period_end]').val(f(e))}
function newPlan(){$('#planForm')[0].reset();$('#plan_id').val('');setDefaultDates();$('#planError').addClass('d-none')}
function editPlan(id){let p=plans.find(x=>x.id==id);newPlan();$('#plan_id').val(id);for(let k of ['user_id','title','description','period_start','period_end','period_type','status'])$(`[name=${k}]`).val(p[k]??'');bootstrap.Modal.getOrCreateInstance(document.getElementById('planModal')).show()}
function addTask(id){$('#taskForm')[0].reset();$('#task_plan_id').val(id);$('#taskError').addClass('d-none');bootstrap.Modal.getOrCreateInstance(document.getElementById('taskModal')).show()}
$('#planForm').on('submit',function(e){e.preventDefault();let id=$('#plan_id').val(),data=Object.fromEntries(new FormData(this).entries());$.ajax({url:id?'{{ url('/ajax/plans') }}/'+id:'{{ route('plans.store') }}',method:id?'PATCH':'POST',data}).done(()=>{bootstrap.Modal.getInstance(document.getElementById('planModal')).hide();loadPlans()}).fail(r=>$('#planError').removeClass('d-none').text(r.responseJSON?.message||'Ошибка сохранения'))});
$('#taskForm').on('submit',function(e){e.preventDefault();let id=$('#task_plan_id').val(),data=Object.fromEntries(new FormData(this).entries());$.post('{{ url('/ajax/plans') }}/'+id+'/tasks',data).done(()=>{bootstrap.Modal.getInstance(document.getElementById('taskModal')).hide();loadPlans()}).fail(r=>$('#taskError').removeClass('d-none').text(r.responseJSON?.message||'Ошибка добавления'))});
let timer;$('#q').on('input',()=>{clearTimeout(timer);timer=setTimeout(loadPlans,300)});$('#statusFilter,#periodFilter,#userFilter').on('change',loadPlans);loadPlans();
</script>
@endpush
