@extends('layouts.app')
@section('title','Задачи — CRM ЗЦРБ')
@section('header','Задачи')
@section('content')
<div class="d-flex gap-2 mb-3 flex-wrap">
  <input id="taskQ" class="form-control" style="max-width:260px" placeholder="Поиск задач">
  <select id="statusFilter" class="form-select" style="max-width:180px"><option value="">Все статусы</option><option value="new">Новая</option><option value="in_progress">В работе</option><option value="review">На проверке</option><option value="completed">Выполнена</option><option value="cancelled">Отменена</option></select>
  <select id="priorityFilter" class="form-select" style="max-width:180px"><option value="">Все приоритеты</option><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option><option value="critical">Критический</option></select>
  @if(auth()->user()->isManager())<select id="assigneeFilter" class="form-select" style="max-width:240px"><option value="">Все исполнители</option>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select>@endif
  <div class="form-check align-self-center"><input class="form-check-input" type="checkbox" id="overdueFilter"><label class="form-check-label">Только просроченные</label></div>
  @if(auth()->user()->isManager())<a href="{{ route('task-templates.page') }}" class="btn btn-outline-primary ms-auto"><i class="bi bi-repeat me-1"></i>Шаблоны</a>@endif
  <button class="btn btn-primary {{ auth()->user()->isManager()?'':'ms-auto' }}" data-bs-toggle="modal" data-bs-target="#taskModal"><i class="bi bi-plus-lg me-1"></i>Новая задача</button>
</div>
<div id="taskList" class="row g-3"></div>

<div class="modal fade" id="taskModal" tabindex="-1"><div class="modal-dialog modal-lg"><form id="taskForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Новая задача</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">Название</label><input name="title" class="form-control" required></div><div class="col-md-4"><label class="form-label">Исполнитель</label><select name="assigned_to" class="form-select" required>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Описание</label><textarea name="description" class="form-control" rows="4"></textarea></div><div class="col-md-4"><label class="form-label">Приоритет</label><select name="priority" class="form-select"><option value="normal">Обычный</option><option value="low">Низкий</option><option value="high">Высокий</option><option value="critical">Критический</option></select></div><div class="col-md-4"><label class="form-label">Срок</label><input name="due_at" type="datetime-local" class="form-control"></div></div><div id="taskError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Создать</button></div></form></div></div>

<div class="modal fade" id="taskDetailsModal" tabindex="-1"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><h5 id="detailTitle" class="modal-title"></h5><div id="detailMeta" class="small text-muted"></div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-4"><div class="col-lg-7">
<h6>Описание</h6><div id="detailDescription" class="mb-4"></div>

<div class="d-flex align-items-center mb-2"><h6 class="mb-0">Чек-лист</h6><span id="checklistProgress" class="badge text-bg-light border ms-2"></span></div>
<div id="checklistList" class="mb-2"></div>
<div id="checklistAddBox" class="input-group input-group-sm mb-4"><input id="checklistTitle" class="form-control" placeholder="Добавить пункт чек-листа"><button class="btn btn-outline-primary" onclick="addChecklistItem()"><i class="bi bi-plus-lg"></i></button></div>

<h6>Отчёт о выполнении</h6><div id="detailResult" class="p-3 bg-light rounded mb-3 text-muted">Отчёт ещё не предоставлен</div><div id="reportBox" class="mb-4"><textarea id="reportText" class="form-control mb-2" rows="4" placeholder="Опишите, что выполнено, результат и важные детали"></textarea><div class="d-flex gap-2"><input id="reportProgress" type="number" min="1" max="100" value="100" class="form-control" style="max-width:120px"><button class="btn btn-primary" onclick="submitReview()"><i class="bi bi-send me-1"></i>Отправить на проверку</button></div></div>

<div id="managerReviewBox" class="border rounded p-3 mb-4 d-none"><h6>Решение руководителя</h6><textarea id="reviewMessage" class="form-control mb-2" rows="3" placeholder="Комментарий руководителя"></textarea><div class="d-flex gap-2"><button class="btn btn-success" onclick="acceptTask()"><i class="bi bi-check-lg me-1"></i>Принять</button><button class="btn btn-outline-danger" onclick="rejectTask()"><i class="bi bi-arrow-counterclockwise me-1"></i>Вернуть на доработку</button></div></div>

<h6>Вложения</h6><div class="input-group mb-3"><input id="attachmentFile" type="file" class="form-control" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.rtf,.jpg,.jpeg,.png,.webp,.zip,.rar,.7z"><button class="btn btn-outline-primary" onclick="uploadAttachment()"><i class="bi bi-paperclip me-1"></i>Загрузить</button></div><div class="small text-muted mb-2">Максимальный размер файла — 20 МБ.</div><div id="attachmentsList" class="mb-4"></div>

<h6>Комментарии</h6><div class="input-group mb-3"><input id="commentBody" class="form-control" placeholder="Добавить комментарий"><button class="btn btn-outline-primary" onclick="addComment()">Отправить</button></div><div id="commentsList"></div>
</div><div class="col-lg-5">
<div id="deadlineBox" class="border rounded p-3 mb-4"><h6>Срок выполнения</h6><div id="currentDeadline" class="fw-semibold mb-2"></div><div class="row g-2"><div class="col-12"><input id="newDeadline" type="datetime-local" class="form-control"></div><div class="col-12"><textarea id="deadlineReason" class="form-control" rows="2" placeholder="Причина переноса срока — обязательна"></textarea></div><div class="col-12"><button class="btn btn-outline-primary btn-sm" onclick="changeDeadline()"><i class="bi bi-calendar2-event me-1"></i>Изменить срок</button></div></div></div>
<h6>История сроков</h6><div id="deadlineHistory" class="list-group list-group-flush mb-4"></div>
<h6>История задачи</h6><div id="eventsList" class="list-group list-group-flush"></div>
</div></div></div></div></div></div>
@endsection

@push('scripts')
<script>
const currentUserId={{ auth()->id() }}; const isManager={{ auth()->user()->isManager()?'true':'false' }}; let currentTask=null;
function esc(v){return $('<div>').text(v??'').html()}function st(s){return {new:'Новая',in_progress:'В работе',review:'На проверке',completed:'Выполнена',cancelled:'Отменена'}[s]||s}function pr(p){return {low:'Низкий',normal:'Обычный',high:'Высокий',critical:'Критический'}[p]||p}function fileSize(n){if(!n)return'0 Б';const u=['Б','КБ','МБ','ГБ'];let i=0,v=n;while(v>=1024&&i<u.length-1){v/=1024;i++}return `${v.toFixed(i?1:0)} ${u[i]}`}
function localInputDate(v){if(!v)return'';const d=new Date(v),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function loadTasks(){let d={q:$('#taskQ').val(),status:$('#statusFilter').val(),priority:$('#priorityFilter').val(),overdue:$('#overdueFilter').is(':checked')?1:0};if($('#assigneeFilter').length)d.assigned_to=$('#assigneeFilter').val();$.get('{{ route('tasks.index') }}',d,r=>{let h='';r.data.forEach(t=>{let over=t.is_overdue;h+=`<div class="col-12"><div class="card border-0 shadow-sm ${over?'task-overdue':''}"><div class="card-body"><div class="d-flex justify-content-between gap-3"><div><div class="fw-semibold fs-5">${esc(t.title)}</div><div class="text-muted small">${esc((t.assignee?.last_name||'')+' '+(t.assignee?.first_name||''))} · ${esc(t.assignee?.department?.name||'Без подразделения')}</div></div><div class="text-end"><span class="badge text-bg-light border">${pr(t.priority)}</span> <span class="badge ${t.status==='review'?'text-bg-warning':'text-bg-primary'}">${st(t.status)}</span></div></div><p class="mt-3 mb-2">${esc(t.description||'')}</p><div class="d-flex align-items-center gap-3 flex-wrap"><div class="progress flex-grow-1" style="min-width:180px;height:9px"><div class="progress-bar" style="width:${t.progress||0}%"></div></div><span class="small">${t.progress||0}%</span><span class="small ${over?'text-danger fw-semibold':'text-muted'}">${t.due_at?'Срок: '+new Date(t.due_at).toLocaleString('ru-RU'):'Без срока'}</span><button class="btn btn-sm btn-outline-primary ms-auto" onclick="openTask(${t.id})">Открыть</button></div></div></div></div>`});$('#taskList').html(h||'<div class="col-12"><div class="alert alert-light border text-center">Задач не найдено</div></div>')})}
function openTask(id){$.get('{{ url('/ajax/tasks') }}/'+id,t=>{currentTask=t;$('#detailTitle').text(t.title);$('#detailMeta').text(`${st(t.status)} · ${pr(t.priority)} · ${(t.assignee?.last_name||'')} ${(t.assignee?.first_name||'')}`);$('#detailDescription').text(t.description||'—');$('#detailResult').toggleClass('text-muted',!t.result).text(t.result||'Отчёт ещё не предоставлен');$('#reportText').val(t.result||'');$('#reportProgress').val(t.progress||100);$('#reportBox').toggle(t.assigned_to===currentUserId&&!['review','completed','cancelled'].includes(t.status));$('#managerReviewBox').toggleClass('d-none',!(isManager&&t.status==='review'));$('#checklistAddBox').toggle(isManager||t.created_by===currentUserId);$('#deadlineBox').toggle(isManager||t.created_by===currentUserId);$('#currentDeadline').text(t.due_at?new Date(t.due_at).toLocaleString('ru-RU'):'Срок не задан');$('#newDeadline').val(localInputDate(t.due_at));$('#deadlineReason').val('');renderChecklist(t.checklist_items||[],t);renderDeadlineHistory(t.deadline_changes||[]);renderAttachments(t.attachments||[]);renderComments(t.comments||[]);renderEvents(t.events||[]);bootstrap.Modal.getOrCreateInstance(document.getElementById('taskDetailsModal')).show()}).fail(showError)}
function renderChecklist(items,t){const done=items.filter(x=>x.is_done).length;$('#checklistProgress').text(items.length?`${done}/${items.length} · ${Math.round(done/items.length*100)}%`:'нет пунктов');$('#checklistList').html(items.length?items.map(i=>`<label class="d-flex align-items-start gap-2 border rounded p-2 mb-2"><input type="checkbox" class="form-check-input mt-1" ${i.is_done?'checked':''} ${['completed','cancelled'].includes(t.status)?'disabled':''} onchange="toggleChecklist(${i.id},this.checked)"><span class="flex-grow-1 ${i.is_done?'text-decoration-line-through text-muted':''}">${esc(i.title)}${i.is_done&&i.completed_at?`<div class="small text-muted">${esc(i.completed_by?.last_name||'')} · ${new Date(i.completed_at).toLocaleString('ru-RU')}</div>`:''}</span></label>`).join(''):'<div class="text-muted mb-2">Чек-лист пуст</div>')}
function addChecklistItem(){if(!currentTask)return;const title=$('#checklistTitle').val().trim();if(!title)return;$.post(`{{ url('/ajax/tasks') }}/${currentTask.id}/checklist`,{title}).done(()=>{$('#checklistTitle').val('');refreshCurrent()}).fail(showError)}
function toggleChecklist(id,done){if(!currentTask)return;$.ajax({url:`{{ url('/ajax/tasks') }}/${currentTask.id}/checklist/${id}`,method:'PATCH',data:{is_done:done?1:0}}).done(refreshCurrent).fail(showError)}
function changeDeadline(){if(!currentTask)return;const reason=$('#deadlineReason').val().trim();if(reason.length<3){alert('Укажите причину переноса срока');return}$.post(`{{ url('/ajax/tasks') }}/${currentTask.id}/deadline`,{due_at:$('#newDeadline').val(),reason}).done(refreshCurrent).fail(showError)}
function renderDeadlineHistory(a){$('#deadlineHistory').html(a.length?a.map(x=>`<div class="list-group-item px-0"><div class="small"><b>${x.old_due_at?new Date(x.old_due_at).toLocaleString('ru-RU'):'не задан'}</b> → <b>${x.new_due_at?new Date(x.new_due_at).toLocaleString('ru-RU'):'без срока'}</b></div><div class="small">${esc(x.reason)}</div><div class="text-muted" style="font-size:12px">${esc((x.user?.last_name||'')+' '+(x.user?.first_name||''))} · ${new Date(x.created_at).toLocaleString('ru-RU')}</div></div>`).join(''):'<div class="text-muted mb-3">Срок ещё не переносился</div>')}
function renderAttachments(a){$('#attachmentsList').html(a.length?a.map(x=>`<div class="border rounded p-2 mb-2 d-flex align-items-center gap-2"><i class="bi bi-file-earmark fs-5"></i><div class="flex-grow-1 min-w-0"><div class="fw-semibold text-truncate">${esc(x.original_name)}</div><div class="small text-muted">${fileSize(x.size)} · ${esc((x.user?.last_name||'')+' '+(x.user?.first_name||''))}</div></div><a class="btn btn-sm btn-outline-secondary" href="{{ url('/attachments') }}/${x.id}/download"><i class="bi bi-download"></i></a><button class="btn btn-sm btn-outline-danger" onclick="deleteAttachment(${x.id})"><i class="bi bi-trash"></i></button></div>`).join(''):'<div class="text-muted">Файлов пока нет</div>')}
function uploadAttachment(){if(!currentTask)return;let f=$('#attachmentFile')[0].files[0];if(!f){alert('Выберите файл');return}let fd=new FormData();fd.append('file',f);$.ajax({url:`{{ url('/ajax/tasks') }}/${currentTask.id}/attachments`,method:'POST',data:fd,processData:false,contentType:false}).done(()=>{$('#attachmentFile').val('');refreshCurrent()}).fail(showError)}
function deleteAttachment(id){if(!confirm('Удалить файл?'))return;$.ajax({url:`{{ url('/ajax/attachments') }}/${id}`,method:'DELETE'}).done(refreshCurrent).fail(showError)}
function renderComments(a){$('#commentsList').html(a.length?a.map(c=>`<div class="border rounded p-2 mb-2"><div class="small fw-semibold">${esc((c.user?.last_name||'')+' '+(c.user?.first_name||''))}<span class="text-muted fw-normal ms-2">${new Date(c.created_at).toLocaleString('ru-RU')}</span></div><div>${esc(c.body)}</div></div>`).join(''):'<div class="text-muted">Комментариев пока нет</div>')}
function renderEvents(a){$('#eventsList').html(a.length?a.map(x=>`<div class="list-group-item px-0"><div class="small fw-semibold">${esc(eventLabel(x.type))}</div><div class="small">${esc(x.message||'')}</div><div class="text-muted" style="font-size:12px">${esc((x.user?.last_name||'')+' '+(x.user?.first_name||''))} · ${new Date(x.created_at).toLocaleString('ru-RU')}</div></div>`).join(''):'<div class="text-muted">История пока пуста</div>')}
function eventLabel(t){return {created:'Создание',updated:'Изменение',comment:'Комментарий',submitted_for_review:'Отправлено на проверку',accepted:'Принято',rejected:'Возвращено на доработку',attachment_added:'Добавлен файл',attachment_deleted:'Удалён файл',checklist_added:'Чек-лист',checklist_toggled:'Чек-лист',deadline_changed:'Перенос срока'}[t]||t}
function refreshCurrent(){if(currentTask)openTask(currentTask.id);loadTasks()}
function submitReview(){if(!currentTask)return;$.post(`{{ url('/ajax/tasks') }}/${currentTask.id}/submit-review`,{result:$('#reportText').val(),progress:$('#reportProgress').val()}).done(refreshCurrent).fail(showError)}
function acceptTask(){if(!currentTask)return;$.post(`{{ url('/ajax/tasks') }}/${currentTask.id}/accept`,{message:$('#reviewMessage').val()}).done(()=>{$('#reviewMessage').val('');refreshCurrent()}).fail(showError)}
function rejectTask(){if(!currentTask)return;let m=$('#reviewMessage').val().trim();if(m.length<3){alert('Укажите замечание при возврате');return}$.post(`{{ url('/ajax/tasks') }}/${currentTask.id}/reject`,{message:m}).done(()=>{$('#reviewMessage').val('');refreshCurrent()}).fail(showError)}
function addComment(){if(!currentTask)return;let b=$('#commentBody').val().trim();if(!b)return;$.post(`{{ url('/ajax/tasks') }}/${currentTask.id}/comments`,{body:b}).done(()=>{$('#commentBody').val('');refreshCurrent()}).fail(showError)}
function showError(x){let m=x.responseJSON?.message||'Ошибка выполнения операции';if(x.responseJSON?.errors){m=Object.values(x.responseJSON.errors).flat().join('\n')}alert(m)}
$('#taskQ').on('input',()=>{clearTimeout(window.tt);window.tt=setTimeout(loadTasks,300)});$('#statusFilter,#priorityFilter,#assigneeFilter,#overdueFilter').on('change',loadTasks);$('#taskForm').on('submit',function(e){e.preventDefault();let d=Object.fromEntries(new FormData(this).entries());$.post('{{ route('tasks.store') }}',d).done(()=>{this.reset();bootstrap.Modal.getInstance(document.getElementById('taskModal')).hide();loadTasks()}).fail(x=>$('#taskError').removeClass('d-none').text(x.responseJSON?.message||'Ошибка создания'))});
const qs=new URLSearchParams(window.location.search);if($('#assigneeFilter').length&&qs.get('assigned_to'))$('#assigneeFilter').val(qs.get('assigned_to'));loadTasks();if(qs.get('task'))setTimeout(()=>openTask(qs.get('task')),150);
</script>
@endpush
