@extends('layouts.app')
@section('title','Задачи — CRM ЗЦРБ')
@section('header','Задачи')
@section('content')
<div class="d-flex gap-2 mb-3 flex-wrap"><input id="taskQ" class="form-control" style="max-width:260px" placeholder="Поиск задач"><select id="statusFilter" class="form-select" style="max-width:180px"><option value="">Все статусы</option><option value="new">Новая</option><option value="in_progress">В работе</option><option value="review">На проверке</option><option value="completed">Выполнена</option><option value="cancelled">Отменена</option></select><select id="priorityFilter" class="form-select" style="max-width:180px"><option value="">Все приоритеты</option><option value="low">Низкий</option><option value="normal">Обычный</option><option value="high">Высокий</option><option value="critical">Критический</option></select>@if(auth()->user()->isManager())<select id="assigneeFilter" class="form-select" style="max-width:240px"><option value="">Все исполнители</option>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select>@endif<div class="form-check align-self-center"><input class="form-check-input" type="checkbox" id="overdueFilter"><label class="form-check-label">Только просроченные</label></div><button class="btn btn-primary ms-auto" data-bs-toggle="modal" data-bs-target="#taskModal"><i class="bi bi-plus-lg me-1"></i>Новая задача</button></div>
<div id="taskList" class="row g-3"></div>
<div class="modal fade" id="taskModal" tabindex="-1"><div class="modal-dialog modal-lg"><form id="taskForm" class="modal-content"><div class="modal-header"><h5 class="modal-title">Новая задача</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-8"><label class="form-label">Название</label><input name="title" class="form-control" required></div><div class="col-md-4"><label class="form-label">Исполнитель</label><select name="assigned_to" class="form-select" required>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->full_name }}</option>@endforeach</select></div><div class="col-12"><label class="form-label">Описание</label><textarea name="description" class="form-control" rows="4"></textarea></div><div class="col-md-4"><label class="form-label">Приоритет</label><select name="priority" class="form-select"><option value="normal">Обычный</option><option value="low">Низкий</option><option value="high">Высокий</option><option value="critical">Критический</option></select></div><div class="col-md-4"><label class="form-label">Срок</label><input name="due_at" type="datetime-local" class="form-control"></div></div><div id="taskError" class="alert alert-danger mt-3 d-none"></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Отмена</button><button class="btn btn-primary">Создать</button></div></form></div></div>
@endsection
@push('scripts')
<script>
function esc(v){return $('<div>').text(v??'').html()}function st(s){return {new:'Новая',in_progress:'В работе',review:'На проверке',completed:'Выполнена',cancelled:'Отменена'}[s]||s}function pr(p){return {low:'Низкий',normal:'Обычный',high:'Высокий',critical:'Критический'}[p]||p}
function loadTasks(){let d={q:$('#taskQ').val(),status:$('#statusFilter').val(),priority:$('#priorityFilter').val(),overdue:$('#overdueFilter').is(':checked')?1:0};if($('#assigneeFilter').length)d.assigned_to=$('#assigneeFilter').val();$.get('{{ route('tasks.index') }}',d,r=>{let h='';r.data.forEach(t=>{let over=t.due_at&&!['completed','cancelled'].includes(t.status)&&new Date(t.due_at)<new Date();h+=`<div class="col-12"><div class="card border-0 shadow-sm ${over?'task-overdue':''}"><div class="card-body"><div class="d-flex justify-content-between gap-3"><div><div class="fw-semibold fs-5">${esc(t.title)}</div><div class="text-muted small">${esc(t.assignee?.last_name+' '+t.assignee?.first_name)} · ${esc(t.assignee?.department?.name||'Без подразделения')}</div></div><div class="text-end"><span class="badge text-bg-light border">${pr(t.priority)}</span> <span class="badge text-bg-primary">${st(t.status)}</span></div></div><p class="mt-3 mb-2">${esc(t.description||'')}</p><div class="d-flex align-items-center gap-3 flex-wrap"><div class="progress flex-grow-1" style="min-width:180px;height:9px"><div class="progress-bar" style="width:${t.progress||0}%"></div></div><span class="small">${t.progress||0}%</span><span class="small ${over?'text-danger fw-semibold':'text-muted'}">${t.due_at?'Срок: '+new Date(t.due_at).toLocaleString('ru-RU'):'Без срока'}</span><select class="form-select form-select-sm" style="width:160px" onchange="changeStatus(${t.id},this.value)"><option value="new" ${t.status==='new'?'selected':''}>Новая</option><option value="in_progress" ${t.status==='in_progress'?'selected':''}>В работе</option><option value="review" ${t.status==='review'?'selected':''}>На проверке</option><option value="completed" ${t.status==='completed'?'selected':''}>Выполнена</option><option value="cancelled" ${t.status==='cancelled'?'selected':''}>Отменена</option></select></div></div></div></div>`});$('#taskList').html(h||'<div class="col-12"><div class="alert alert-light border text-center">Задач не найдено</div></div>')})}
function changeStatus(id,status){$.ajax({url:'{{ url('/ajax/tasks') }}/'+id,method:'PATCH',data:{status}}).done(loadTasks).fail(()=>alert('Не удалось изменить статус'))}
$('#taskQ').on('input',()=>{clearTimeout(window.tt);window.tt=setTimeout(loadTasks,300)});$('#statusFilter,#priorityFilter,#assigneeFilter,#overdueFilter').on('change',loadTasks);$('#taskForm').on('submit',function(e){e.preventDefault();let d=Object.fromEntries(new FormData(this).entries());$.post('{{ route('tasks.store') }}',d).done(()=>{this.reset();bootstrap.Modal.getInstance(document.getElementById('taskModal')).hide();loadTasks()}).fail(x=>$('#taskError').removeClass('d-none').text(x.responseJSON?.message||'Ошибка создания'))});
const qs=new URLSearchParams(window.location.search);if($('#assigneeFilter').length&&qs.get('assigned_to'))$('#assigneeFilter').val(qs.get('assigned_to'));loadTasks();
</script>
@endpush
